# Generated by Django 3.1.5 on 2021-01-14 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20210110_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
