# Generated by Django 3.1.5 on 2021-01-14 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20210114_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.FloatField(),
        ),
    ]
