# Generated by Django 3.1.5 on 2021-01-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20210115_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=False, max_length=5000, null=True),
        ),
    ]
