# Generated by Django 3.1.5 on 2021-01-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
