# Generated by Django 3.1.5 on 2021-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_auto_20210115_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='opinion',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.IntegerField(),
        ),
    ]
