# Generated by Django 3.1.5 on 2021-01-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_auto_20210120_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
