# Generated by Django 3.1.5 on 2021-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
