# Generated by Django 3.1.5 on 2021-01-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0013_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
