# Generated by Django 3.1.5 on 2021-01-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0014_remove_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
