# Generated by Django 3.1.5 on 2021-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0015_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
