# Generated by Django 3.1.5 on 2021-01-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0020_auto_20210126_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
