# Generated by Django 3.1.5 on 2021-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0023_auto_20210128_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
