# Generated by Django 3.1.5 on 2021-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0025_auto_20210201_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
